### ISSUE TITLE
Hp / Health problem

### ISSUE THREAD

**Issue by kkotyiTheSmith** [kkotyiTheSmith/TheHolyBier#20]
In GCharacter.java there are two variables for health. And in Player.java another maxHp is introduced. I think it is possible to convert this to only 2 variables.

**Comment by JaviCan1** [comment]
Sorry for the misunderstanding, maxHp should be called totalHp, and it is he sum of the player Hp and its items. When showing stats, only the totalHp should be shown along with health regarding player life.
