### ISSUE TITLE
Creating the level up system

### ISSUE THREAD

**Issue by kkotyiTheSmith** [kkotyiTheSmith/TheHolyBier#22]
I imagine it in such a way that whenever the xp is increased in Player.java, the code should check if there is enough xp for the next level up.

**Comment by JaviCan1** [comment]
Done already, it does check it on paper, yet have to test it once the combat is partially finished.

**Comment by kkotyiTheSmith** [comment]
Combat system IS finished. Only your part, the balancing is left.

**Comment by JaviCan1** [comment]
Everything finished
